import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/sidebar/sidebar";
import { Menu } from "lucide-react";
import { Button } from "@/components/ui/button";
import {
    Sheet,
    SheetTitle,
    SheetContent,
    SheetTrigger,
} from "@/components/ui/sheet";
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <div className="flex h-screen overflow-hidden bg-background">
                    {/* Desktop Sidebar */}
                    <div className="hidden md:block">
                        <Sidebar />
                    </div>

                    <div className="flex flex-1 flex-col overflow-hidden">
                        <header className="flex h-16 items-center justify-between border-b px-6">
                            <div className="flex items-center gap-4">
                                {/* Mobile Sidebar Trigger */}
                                <Sheet>
                                    <SheetTrigger asChild>
                                        <Button
                                            variant="outline"
                                            size="icon"
                                            className="md:hidden h-9 w-9 rounded-full border-primary/20"
                                            aria-label="Open menu"
                                        >
                                            <Menu className="h-5 w-5 text-primary" />
                                        </Button>
                                    </SheetTrigger>
                                    <SheetContent
                                        side="left"
                                        className="p-0 w-[280px]"
                                    >
                                        <SheetTitle className="sr-only">
                                            Navigation Menu
                                        </SheetTitle>
                                        <Sidebar isMobile={true} />
                                    </SheetContent>
                                </Sheet>
                                <h1 className="text-xl font-bold">
                                    Hi Tradies Management
                                </h1>
                            </div>
                        </header>
                        <main className="flex-1 overflow-auto p-6">
                            {children}
                        </main>
                    </div>
                </div>
            </body>
        </html>
    );
}
